cargo-features = ["profile-rustflags"]

[package]
name = "particlinator"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
bevy_math = "0.16.1"
bytemuck = { version = "1.23.0", features = ["min_const_generics"] }
egui = "0.31.1"
egui-wgpu = "0.31.1"
egui-winit = "0.31.1"
env_logger = "0.11.8"
image = "0.25.6"
log = { version = "0.4.27", features = [
    "max_level_debug",
    "release_max_level_warn",
] }
pollster = "0.4.0"
rfd = "0.15.3"
serde = "1.0.219"
wgpu = "24.0.1"
winit = "0.30.11"
